package persistence

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go/modules/postgres"
)

// This test requires Docker/Podman. It creates a fresh Postgres container,
// applies the sessions schema, and exercises the SessionRepository against it.
func TestSessionRepositoryIntegration(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in short mode")
	}
	ctx := context.Background()

	// Boot Postgres container.
	pgContainer, err := postgres.Run(ctx,
		"postgres:16-alpine",
		postgres.WithDatabase("testdb"),
		postgres.WithUsername("test"),
		postgres.WithPassword("test"),
	)
	require.NoError(t, err)
	t.Cleanup(func() { _ = pgContainer.Terminate(ctx) })

	connStr, err := pgContainer.ConnectionString(ctx, "sslmode=disable")
	require.NoError(t, err)

	pool, err := pgxpool.New(ctx, connStr)
	require.NoError(t, err)
	defer pool.Close()

	// Wait for DB readiness (Windows Docker quirk).
	waitForDB(t, ctx, pool)

	// Create schema — users table + sessions table, matching the core migrations.
	_, err = pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS plt_users (
			id               UUID         PRIMARY KEY,
			username         VARCHAR(255) NOT NULL UNIQUE,
			email            VARCHAR(255) NOT NULL UNIQUE,
			password_hash    VARCHAR(255) NOT NULL,
			role             VARCHAR(50)  NOT NULL DEFAULT 'USER',
			enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
			created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
			last_activity_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
		);
		CREATE TABLE IF NOT EXISTS plt_sessions (
			id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			token_hash VARCHAR(64)  NOT NULL,
			user_id    UUID         NOT NULL,
			created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
			expires_at TIMESTAMP    NOT NULL,
			FOREIGN KEY (user_id) REFERENCES plt_users(id) ON DELETE CASCADE
		);
		CREATE UNIQUE INDEX IF NOT EXISTS ux_plt_sessions_token_hash ON plt_sessions(token_hash);
	`)
	require.NoError(t, err)

	// Insert a test user that sessions will reference.
	userID := uuid.MustParse("550e8400-e29b-41d4-a716-446655440000")
	_, err = pool.Exec(ctx, `
		INSERT INTO plt_users (id, username, email, password_hash)
		VALUES ($1, 'testuser', 'test@test.com', 'hash')
	`, userID)
	require.NoError(t, err)

	repo := NewSessionRepository(pool)

	t.Run("create_find_delete_lifecycle", func(t *testing.T) {
		tokenHash := "aabbccdd" + uuid.NewString()[:16]
		// Use UTC: the DB column is TIMESTAMP (without TZ), so we must pass a
		// wall-clock instant that agrees with the DB server's CURRENT_TIMESTAMP
		// for the expiry-filtering queries to behave correctly.
		expiresAt := time.Now().UTC().Add(1 * time.Hour)

		// 1. Create a session.
		created, err := repo.CreateSession(ctx, tokenHash, userID, expiresAt)
		require.NoError(t, err)
		assert.Equal(t, tokenHash, created.TokenHash)
		assert.Equal(t, userID, created.UserID)
		assertInstantsClose(t, created.ExpiresAt.Time, expiresAt)

		// 2. Find it by token hash.
		found, err := repo.FindByTokenHash(ctx, tokenHash)
		require.NoError(t, err)
		assert.Equal(t, userID, found.UserID)
		assert.Equal(t, tokenHash, found.TokenHash)

		// 3. Find it including expired (should also work).
		foundInc, err := repo.FindByTokenHashIncludingExpired(ctx, tokenHash)
		require.NoError(t, err)
		assert.Equal(t, tokenHash, foundInc.TokenHash)

		// 4. Delete it by token hash.
		err = repo.DeleteByTokenHash(ctx, tokenHash)
		require.NoError(t, err)

		// 5. Verify it's gone from FindByTokenHash.
		_, err = repo.FindByTokenHash(ctx, tokenHash)
		assert.Error(t, err, "session should be deleted")

		// 6. Verify it's gone from FindByTokenHashIncludingExpired too.
		_, err = repo.FindByTokenHashIncludingExpired(ctx, tokenHash)
		assert.Error(t, err, "session should be deleted")
	})

	t.Run("expired_session_not_returned_by_FindByTokenHash", func(t *testing.T) {
		tokenHash := "expired-" + uuid.NewString()[:16]
		// Create a session that already expired (UTC for TZ-less column).
		expiredAt := time.Now().UTC().Add(-1 * time.Hour)
		_, err := repo.CreateSession(ctx, tokenHash, userID, expiredAt)
		require.NoError(t, err)

		// FindByTokenHash filters out expired sessions (expires_at > CURRENT_TIMESTAMP).
		_, err = repo.FindByTokenHash(ctx, tokenHash)
		assert.Error(t, err, "expired session should not be returned by FindByTokenHash")

		// But FindByTokenHashIncludingExpired returns it.
		found, err := repo.FindByTokenHashIncludingExpired(ctx, tokenHash)
		require.NoError(t, err)
		assert.Equal(t, tokenHash, found.TokenHash)
	})

	t.Run("DeleteExpired_removes_only_expired_sessions", func(t *testing.T) {
		// Active session: should survive.
		activeToken := "active-" + uuid.NewString()[:16]
		_, err := repo.CreateSession(ctx, activeToken, userID, time.Now().UTC().Add(1*time.Hour))
		require.NoError(t, err)

		// Expired session: should be reaped.
		expiredToken := "reap-" + uuid.NewString()[:16]
		_, err = repo.CreateSession(ctx, expiredToken, userID, time.Now().UTC().Add(-1*time.Hour))
		require.NoError(t, err)

		deleted, err := repo.DeleteExpired(ctx)
		require.NoError(t, err)
		assert.GreaterOrEqual(t, deleted, int64(1), "at least the expired session should be deleted")

		// Active session survives.
		_, err = repo.FindByTokenHashIncludingExpired(ctx, activeToken)
		assert.NoError(t, err, "active session should survive DeleteExpired")

		// Expired session is gone.
		_, err = repo.FindByTokenHashIncludingExpired(ctx, expiredToken)
		assert.Error(t, err, "expired session should be reaped")
	})

	t.Run("UpdateExpiresAt_extends_session", func(t *testing.T) {
		tokenHash := "extend-" + uuid.NewString()[:16]
		_, err := repo.CreateSession(ctx, tokenHash, userID, time.Now().UTC().Add(5*time.Minute))
		require.NoError(t, err)

		newExpiry := time.Now().UTC().Add(24 * time.Hour)
		updated, err := repo.UpdateExpiresAt(ctx, tokenHash, newExpiry)
		require.NoError(t, err)
		assertInstantsClose(t, updated.ExpiresAt.Time, newExpiry)

		// Now FindByTokenHash works again (was close to expiry, now far future).
		found, err := repo.FindByTokenHash(ctx, tokenHash)
		require.NoError(t, err)
		assert.Equal(t, tokenHash, found.TokenHash)
	})

	t.Run("DeleteByUserID_removes_all_sessions_for_user", func(t *testing.T) {
		tok1 := "byuser1-" + uuid.NewString()[:16]
		tok2 := "byuser2-" + uuid.NewString()[:16]
		_, err := repo.CreateSession(ctx, tok1, userID, time.Now().UTC().Add(1*time.Hour))
		require.NoError(t, err)
		_, err = repo.CreateSession(ctx, tok2, userID, time.Now().UTC().Add(1*time.Hour))
		require.NoError(t, err)

		err = repo.DeleteByUserID(ctx, userID)
		require.NoError(t, err)

		_, err = repo.FindByTokenHashIncludingExpired(ctx, tok1)
		assert.Error(t, err, "session 1 should be deleted")
		_, err = repo.FindByTokenHashIncludingExpired(ctx, tok2)
		assert.Error(t, err, "session 2 should be deleted")
	})
}

// waitForDB polls the connection until the pool can acquire a connection and
// run a trivial query. The postgres Testcontainers module reports readiness
// before the server reliably accepts connections on some hosts (notably
// Docker Desktop on Windows), so we gate the test on an actual round-trip.
func waitForDB(t *testing.T, ctx context.Context, pool *pgxpool.Pool) {
	t.Helper()
	deadline := time.Now().Add(30 * time.Second)
	for {
		if err := pool.Ping(ctx); err == nil {
			return
		}
		if time.Now().After(deadline) {
			t.Fatalf("database did not become reachable within 30s")
		}
		time.Sleep(500 * time.Millisecond)
	}
}

// assertInstantsClose compares the wall-clock instants of two times, ignoring
// the monotonic clock reading that time.Now() attaches. This is required when
// comparing a time.Time produced by time.Now() (which carries a monotonic
// component) against a timestamp read back from Postgres (which does not).
// Both sides are converted to UTC and compared to within a 2-second tolerance.
func assertInstantsClose(t *testing.T, got, want time.Time) {
	t.Helper()
	gotUTC := got.UTC()
	wantUTC := want.UTC()
	diff := gotUTC.Sub(wantUTC)
	if diff < 0 {
		diff = -diff
	}
	if diff > 2*time.Second {
		t.Errorf("instants not close: got %v want %v (diff %v)", gotUTC, wantUTC, diff)
	}
}
