// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO plt_api_keys (user_id, key_hash, key_prefix, name, enabled)
VALUES ($1, $2, $3, $4, true)
RETURNING id, user_id, key_hash, key_prefix, name, enabled, created_at, last_used_at
`

type CreateApiKeyParams struct {
	UserID    uuid.UUID `json:"user_id"`
	KeyHash   string    `json:"key_hash"`
	KeyPrefix string    `json:"key_prefix"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (PltApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.UserID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Name,
	)
	var i PltApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :execrows
DELETE FROM plt_api_keys WHERE id = $1 AND user_id = $2
`

type DeleteApiKeyParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApiKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findApiKeyByHash = `-- name: FindApiKeyByHash :one
SELECT id, user_id, key_hash, key_prefix, name, enabled, created_at, last_used_at
FROM plt_api_keys
WHERE key_hash = $1 AND enabled = true
`

func (q *Queries) FindApiKeyByHash(ctx context.Context, keyHash string) (PltApiKey, error) {
	row := q.db.QueryRow(ctx, findApiKeyByHash, keyHash)
	var i PltApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const findApiKeysByUserID = `-- name: FindApiKeysByUserID :many
SELECT id, user_id, key_hash, key_prefix, name, enabled, created_at, last_used_at
FROM plt_api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) FindApiKeysByUserID(ctx context.Context, userID uuid.UUID) ([]PltApiKey, error) {
	rows, err := q.db.Query(ctx, findApiKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltApiKey{}
	for rows.Next() {
		var i PltApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Name,
			&i.Enabled,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE plt_api_keys SET last_used_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateApiKeyLastUsed, id)
	return err
}
