// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllAudit = `-- name: CountAllAudit :one
SELECT COUNT(*) FROM plt_audit_log
`

func (q *Queries) CountAllAudit(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllAudit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAuditPage = `-- name: FindAuditPage :many
SELECT id, actor_id, actor_username, target_id, target_username, action, detail, created_at
FROM plt_audit_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type FindAuditPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindAuditPage(ctx context.Context, arg FindAuditPageParams) ([]PltAuditLog, error) {
	rows, err := q.db.Query(ctx, findAuditPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltAuditLog{}
	for rows.Next() {
		var i PltAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorUsername,
			&i.TargetID,
			&i.TargetUsername,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRecentAudit = `-- name: FindRecentAudit :many
SELECT id, actor_id, actor_username, target_id, target_username, action, detail, created_at
FROM plt_audit_log
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) FindRecentAudit(ctx context.Context, limit int32) ([]PltAuditLog, error) {
	rows, err := q.db.Query(ctx, findRecentAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltAuditLog{}
	for rows.Next() {
		var i PltAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorUsername,
			&i.TargetID,
			&i.TargetUsername,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAudit = `-- name: LogAudit :one
INSERT INTO plt_audit_log (actor_id, actor_username, target_id, target_username, action, detail)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_id, actor_username, target_id, target_username, action, detail, created_at
`

type LogAuditParams struct {
	ActorID        pgtype.UUID `json:"actor_id"`
	ActorUsername  *string     `json:"actor_username"`
	TargetID       pgtype.UUID `json:"target_id"`
	TargetUsername *string     `json:"target_username"`
	Action         string      `json:"action"`
	Detail         *string     `json:"detail"`
}

func (q *Queries) LogAudit(ctx context.Context, arg LogAuditParams) (PltAuditLog, error) {
	row := q.db.QueryRow(ctx, logAudit,
		arg.ActorID,
		arg.ActorUsername,
		arg.TargetID,
		arg.TargetUsername,
		arg.Action,
		arg.Detail,
	)
	var i PltAuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ActorUsername,
		&i.TargetID,
		&i.TargetUsername,
		&i.Action,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}
