// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"
)

const countContacts = `-- name: CountContacts :one
SELECT COUNT(*) FROM plt_contacts WHERE deleted = false
`

func (q *Queries) CountContacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countContacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchContacts = `-- name: CountSearchContacts :one
SELECT COUNT(*) FROM plt_contacts
WHERE deleted = false
AND (name ILIKE '%' || $1::text || '%' OR COALESCE(company, '') ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountSearchContacts(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchContacts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocalContact = `-- name: CreateLocalContact :one
INSERT INTO plt_contacts (sync_id, name, company, company_address, department, updated_at_epoch_ms, dirty, deleted, version)
VALUES ($1, $2, $3, $4, $5, $6, true, false, 1)
RETURNING id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
`

type CreateLocalContactParams struct {
	SyncID           string  `json:"sync_id"`
	Name             string  `json:"name"`
	Company          *string `json:"company"`
	CompanyAddress   *string `json:"company_address"`
	Department       *string `json:"department"`
	UpdatedAtEpochMs int64   `json:"updated_at_epoch_ms"`
}

func (q *Queries) CreateLocalContact(ctx context.Context, arg CreateLocalContactParams) (PltContact, error) {
	row := q.db.QueryRow(ctx, createLocalContact,
		arg.SyncID,
		arg.Name,
		arg.Company,
		arg.CompanyAddress,
		arg.Department,
		arg.UpdatedAtEpochMs,
	)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const createServerContact = `-- name: CreateServerContact :one
INSERT INTO plt_contacts (sync_id, name, company, company_address, department, updated_at_epoch_ms, dirty, deleted, version)
VALUES ($1, $2, $3, $4, $5, $6, false, false, 1)
RETURNING id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
`

type CreateServerContactParams struct {
	SyncID           string  `json:"sync_id"`
	Name             string  `json:"name"`
	Company          *string `json:"company"`
	CompanyAddress   *string `json:"company_address"`
	Department       *string `json:"department"`
	UpdatedAtEpochMs int64   `json:"updated_at_epoch_ms"`
}

func (q *Queries) CreateServerContact(ctx context.Context, arg CreateServerContactParams) (PltContact, error) {
	row := q.db.QueryRow(ctx, createServerContact,
		arg.SyncID,
		arg.Name,
		arg.Company,
		arg.CompanyAddress,
		arg.Department,
		arg.UpdatedAtEpochMs,
	)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const findContactBySyncID = `-- name: FindContactBySyncID :one
SELECT id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
FROM plt_contacts
WHERE sync_id = $1
`

func (q *Queries) FindContactBySyncID(ctx context.Context, syncID string) (PltContact, error) {
	row := q.db.QueryRow(ctx, findContactBySyncID, syncID)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const findContactChangesSince = `-- name: FindContactChangesSince :many
SELECT id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
FROM plt_contacts
WHERE updated_at_epoch_ms > $1
ORDER BY updated_at_epoch_ms ASC
`

func (q *Queries) FindContactChangesSince(ctx context.Context, updatedAtEpochMs int64) ([]PltContact, error) {
	rows, err := q.db.Query(ctx, findContactChangesSince, updatedAtEpochMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltContact{}
	for rows.Next() {
		var i PltContact
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Name,
			&i.Company,
			&i.CompanyAddress,
			&i.Department,
			&i.CreatedAt,
			&i.UpdatedAtEpochMs,
			&i.Deleted,
			&i.Dirty,
			&i.Version,
			&i.SyncConflict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertContactEmail = `-- name: InsertContactEmail :exec
INSERT INTO plt_contact_emails (contact_id, email) VALUES ($1, $2)
`

type InsertContactEmailParams struct {
	ContactID int64  `json:"contact_id"`
	Email     string `json:"email"`
}

func (q *Queries) InsertContactEmail(ctx context.Context, arg InsertContactEmailParams) error {
	_, err := q.db.Exec(ctx, insertContactEmail, arg.ContactID, arg.Email)
	return err
}

const insertContactPhone = `-- name: InsertContactPhone :exec
INSERT INTO plt_contact_phones (contact_id, phone) VALUES ($1, $2)
`

type InsertContactPhoneParams struct {
	ContactID int64  `json:"contact_id"`
	Phone     string `json:"phone"`
}

func (q *Queries) InsertContactPhone(ctx context.Context, arg InsertContactPhoneParams) error {
	_, err := q.db.Exec(ctx, insertContactPhone, arg.ContactID, arg.Phone)
	return err
}

const insertContactSocial = `-- name: InsertContactSocial :exec
INSERT INTO plt_contact_socials (contact_id, social_media) VALUES ($1, $2)
`

type InsertContactSocialParams struct {
	ContactID   int64  `json:"contact_id"`
	SocialMedia string `json:"social_media"`
}

func (q *Queries) InsertContactSocial(ctx context.Context, arg InsertContactSocialParams) error {
	_, err := q.db.Exec(ctx, insertContactSocial, arg.ContactID, arg.SocialMedia)
	return err
}

const listContactEmails = `-- name: ListContactEmails :many
SELECT email FROM plt_contact_emails WHERE contact_id = $1
`

func (q *Queries) ListContactEmails(ctx context.Context, contactID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listContactEmails, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactEmailsBatch = `-- name: ListContactEmailsBatch :many
SELECT contact_id, email FROM plt_contact_emails WHERE contact_id = ANY($1::bigint[])
`

func (q *Queries) ListContactEmailsBatch(ctx context.Context, dollar_1 []int64) ([]PltContactEmail, error) {
	rows, err := q.db.Query(ctx, listContactEmailsBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltContactEmail{}
	for rows.Next() {
		var i PltContactEmail
		if err := rows.Scan(&i.ContactID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactPhones = `-- name: ListContactPhones :many
SELECT phone FROM plt_contact_phones WHERE contact_id = $1
`

func (q *Queries) ListContactPhones(ctx context.Context, contactID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listContactPhones, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var phone string
		if err := rows.Scan(&phone); err != nil {
			return nil, err
		}
		items = append(items, phone)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactPhonesBatch = `-- name: ListContactPhonesBatch :many
SELECT contact_id, phone FROM plt_contact_phones WHERE contact_id = ANY($1::bigint[])
`

func (q *Queries) ListContactPhonesBatch(ctx context.Context, dollar_1 []int64) ([]PltContactPhone, error) {
	rows, err := q.db.Query(ctx, listContactPhonesBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltContactPhone{}
	for rows.Next() {
		var i PltContactPhone
		if err := rows.Scan(&i.ContactID, &i.Phone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactSocials = `-- name: ListContactSocials :many
SELECT social_media FROM plt_contact_socials WHERE contact_id = $1
`

func (q *Queries) ListContactSocials(ctx context.Context, contactID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listContactSocials, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var social_media string
		if err := rows.Scan(&social_media); err != nil {
			return nil, err
		}
		items = append(items, social_media)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactSocialsBatch = `-- name: ListContactSocialsBatch :many
SELECT contact_id, social_media FROM plt_contact_socials WHERE contact_id = ANY($1::bigint[])
`

func (q *Queries) ListContactSocialsBatch(ctx context.Context, dollar_1 []int64) ([]PltContactSocial, error) {
	rows, err := q.db.Query(ctx, listContactSocialsBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltContactSocial{}
	for rows.Next() {
		var i PltContactSocial
		if err := rows.Scan(&i.ContactID, &i.SocialMedia); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
FROM plt_contacts
WHERE deleted = false
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListContactsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]PltContact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltContact{}
	for rows.Next() {
		var i PltContact
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Name,
			&i.Company,
			&i.CompanyAddress,
			&i.Department,
			&i.CreatedAt,
			&i.UpdatedAtEpochMs,
			&i.Deleted,
			&i.Dirty,
			&i.Version,
			&i.SyncConflict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirtyContacts = `-- name: ListDirtyContacts :many
SELECT id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
FROM plt_contacts
WHERE dirty = true AND deleted = false
ORDER BY updated_at_epoch_ms ASC
`

func (q *Queries) ListDirtyContacts(ctx context.Context) ([]PltContact, error) {
	rows, err := q.db.Query(ctx, listDirtyContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltContact{}
	for rows.Next() {
		var i PltContact
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Name,
			&i.Company,
			&i.CompanyAddress,
			&i.Department,
			&i.CreatedAt,
			&i.UpdatedAtEpochMs,
			&i.Deleted,
			&i.Dirty,
			&i.Version,
			&i.SyncConflict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCleanContacts = `-- name: MarkCleanContacts :exec
UPDATE plt_contacts SET dirty = false WHERE dirty = true
`

func (q *Queries) MarkCleanContacts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markCleanContacts)
	return err
}

const markConflictContact = `-- name: MarkConflictContact :one
UPDATE plt_contacts
SET sync_conflict = $2, version = version + 1
WHERE sync_id = $1
RETURNING id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
`

type MarkConflictContactParams struct {
	SyncID       string  `json:"sync_id"`
	SyncConflict *string `json:"sync_conflict"`
}

func (q *Queries) MarkConflictContact(ctx context.Context, arg MarkConflictContactParams) (PltContact, error) {
	row := q.db.QueryRow(ctx, markConflictContact, arg.SyncID, arg.SyncConflict)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const resolveConflictContact = `-- name: ResolveConflictContact :one
UPDATE plt_contacts
SET sync_conflict = NULL, version = version + 1
WHERE sync_id = $1
RETURNING id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
`

func (q *Queries) ResolveConflictContact(ctx context.Context, syncID string) (PltContact, error) {
	row := q.db.QueryRow(ctx, resolveConflictContact, syncID)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const restoreContact = `-- name: RestoreContact :one
UPDATE plt_contacts
SET deleted = false, dirty = true, version = version + 1
WHERE sync_id = $1
RETURNING id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
`

func (q *Queries) RestoreContact(ctx context.Context, syncID string) (PltContact, error) {
	row := q.db.QueryRow(ctx, restoreContact, syncID)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
FROM plt_contacts
WHERE deleted = false
AND (name ILIKE '%' || $1::text || '%' OR COALESCE(company, '') ILIKE '%' || $1::text || '%')
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type SearchContactsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

// Returns one page of non-deleted contacts whose name or company match the
// query (case-insensitive ILIKE). Mirrors SearchMessages. company is nullable,
// so COALESCE protects the ILIKE from NULL operands.
func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]PltContact, error) {
	rows, err := q.db.Query(ctx, searchContacts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltContact{}
	for rows.Next() {
		var i PltContact
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Name,
			&i.Company,
			&i.CompanyAddress,
			&i.Department,
			&i.CreatedAt,
			&i.UpdatedAtEpochMs,
			&i.Deleted,
			&i.Dirty,
			&i.Version,
			&i.SyncConflict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContactEmails = `-- name: SetContactEmails :exec
DELETE FROM plt_contact_emails WHERE contact_id = $1
`

func (q *Queries) SetContactEmails(ctx context.Context, contactID int64) error {
	_, err := q.db.Exec(ctx, setContactEmails, contactID)
	return err
}

const setContactPhones = `-- name: SetContactPhones :exec
DELETE FROM plt_contact_phones WHERE contact_id = $1
`

func (q *Queries) SetContactPhones(ctx context.Context, contactID int64) error {
	_, err := q.db.Exec(ctx, setContactPhones, contactID)
	return err
}

const setContactSocials = `-- name: SetContactSocials :exec
DELETE FROM plt_contact_socials WHERE contact_id = $1
`

func (q *Queries) SetContactSocials(ctx context.Context, contactID int64) error {
	_, err := q.db.Exec(ctx, setContactSocials, contactID)
	return err
}

const softDeleteContact = `-- name: SoftDeleteContact :one
UPDATE plt_contacts
SET deleted = true, dirty = true, version = version + 1
WHERE sync_id = $1
RETURNING id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
`

func (q *Queries) SoftDeleteContact(ctx context.Context, syncID string) (PltContact, error) {
	row := q.db.QueryRow(ctx, softDeleteContact, syncID)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const updateContact = `-- name: UpdateContact :one
UPDATE plt_contacts
SET name = $2, company = $3, company_address = $4, department = $5, updated_at_epoch_ms = $6, dirty = $7, version = version + 1
WHERE sync_id = $1 AND version = $8
RETURNING id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
`

type UpdateContactParams struct {
	SyncID           string  `json:"sync_id"`
	Name             string  `json:"name"`
	Company          *string `json:"company"`
	CompanyAddress   *string `json:"company_address"`
	Department       *string `json:"department"`
	UpdatedAtEpochMs int64   `json:"updated_at_epoch_ms"`
	Dirty            bool    `json:"dirty"`
	Version          int64   `json:"version"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (PltContact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.SyncID,
		arg.Name,
		arg.Company,
		arg.CompanyAddress,
		arg.Department,
		arg.UpdatedAtEpochMs,
		arg.Dirty,
		arg.Version,
	)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const upsertSyncedContact = `-- name: UpsertSyncedContact :one
INSERT INTO plt_contacts (sync_id, name, company, company_address, department, updated_at_epoch_ms, dirty, deleted, version)
VALUES ($1, $2, $3, $4, $5, $6, false, $7, 1)
ON CONFLICT (sync_id) DO UPDATE SET
    name = EXCLUDED.name,
    company = EXCLUDED.company,
    company_address = EXCLUDED.company_address,
    department = EXCLUDED.department,
    updated_at_epoch_ms = EXCLUDED.updated_at_epoch_ms,
    dirty = false,
    deleted = EXCLUDED.deleted,
    version = plt_contacts.version + 1,
    sync_conflict = NULL
RETURNING id, sync_id, name, company, company_address, department, created_at, updated_at_epoch_ms, deleted, dirty, version, sync_conflict
`

type UpsertSyncedContactParams struct {
	SyncID           string  `json:"sync_id"`
	Name             string  `json:"name"`
	Company          *string `json:"company"`
	CompanyAddress   *string `json:"company_address"`
	Department       *string `json:"department"`
	UpdatedAtEpochMs int64   `json:"updated_at_epoch_ms"`
	Deleted          bool    `json:"deleted"`
}

func (q *Queries) UpsertSyncedContact(ctx context.Context, arg UpsertSyncedContactParams) (PltContact, error) {
	row := q.db.QueryRow(ctx, upsertSyncedContact,
		arg.SyncID,
		arg.Name,
		arg.Company,
		arg.CompanyAddress,
		arg.Department,
		arg.UpdatedAtEpochMs,
		arg.Deleted,
	)
	var i PltContact
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.Company,
		&i.CompanyAddress,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}
