// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteAllDeviceTokensForUser = `-- name: DeleteAllDeviceTokensForUser :execrows
DELETE FROM plt_device_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAllDeviceTokensForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllDeviceTokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :execrows
DELETE FROM plt_device_tokens WHERE id = $1 AND user_id = $2
`

type DeleteDeviceTokenParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDeviceTokensByUserID = `-- name: FindDeviceTokensByUserID :many
SELECT id, user_id, platform, token, app_bundle, created_at, last_seen
FROM plt_device_tokens
WHERE user_id = $1
`

func (q *Queries) FindDeviceTokensByUserID(ctx context.Context, userID uuid.UUID) ([]PltDeviceToken, error) {
	rows, err := q.db.Query(ctx, findDeviceTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltDeviceToken{}
	for rows.Next() {
		var i PltDeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Token,
			&i.AppBundle,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO plt_device_tokens (user_id, platform, token, app_bundle)
VALUES ($1, $2, $3, $4)
ON CONFLICT (token) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    app_bundle = EXCLUDED.app_bundle,
    last_seen = CURRENT_TIMESTAMP
RETURNING id, user_id, platform, token, app_bundle, created_at, last_seen
`

type UpsertDeviceTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Platform  string    `json:"platform"`
	Token     string    `json:"token"`
	AppBundle *string   `json:"app_bundle"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (PltDeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken,
		arg.UserID,
		arg.Platform,
		arg.Token,
		arg.AppBundle,
	)
	var i PltDeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Token,
		&i.AppBundle,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}
