// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
)

const countDirtyMessages = `-- name: CountDirtyMessages :one
SELECT COUNT(*) FROM plt_messages WHERE dirty = true AND deleted = false
`

func (q *Queries) CountDirtyMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDirtyMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM plt_messages WHERE deleted = false
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocalMessage = `-- name: CreateLocalMessage :one
INSERT INTO plt_messages (sync_id, author, content, updated_at_epoch_ms, dirty, deleted, version)
VALUES ($1, $2, $3, $4, true, false, 1)
RETURNING id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
`

type CreateLocalMessageParams struct {
	SyncID           string `json:"sync_id"`
	Author           string `json:"author"`
	Content          string `json:"content"`
	UpdatedAtEpochMs int64  `json:"updated_at_epoch_ms"`
}

func (q *Queries) CreateLocalMessage(ctx context.Context, arg CreateLocalMessageParams) (PltMessage, error) {
	row := q.db.QueryRow(ctx, createLocalMessage,
		arg.SyncID,
		arg.Author,
		arg.Content,
		arg.UpdatedAtEpochMs,
	)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const createServerMessage = `-- name: CreateServerMessage :one
INSERT INTO plt_messages (sync_id, author, content, updated_at_epoch_ms, dirty, deleted, version)
VALUES ($1, $2, $3, $4, false, false, 1)
RETURNING id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
`

type CreateServerMessageParams struct {
	SyncID           string `json:"sync_id"`
	Author           string `json:"author"`
	Content          string `json:"content"`
	UpdatedAtEpochMs int64  `json:"updated_at_epoch_ms"`
}

func (q *Queries) CreateServerMessage(ctx context.Context, arg CreateServerMessageParams) (PltMessage, error) {
	row := q.db.QueryRow(ctx, createServerMessage,
		arg.SyncID,
		arg.Author,
		arg.Content,
		arg.UpdatedAtEpochMs,
	)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const findBySyncID = `-- name: FindBySyncID :one
SELECT id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
FROM plt_messages
WHERE sync_id = $1
`

func (q *Queries) FindBySyncID(ctx context.Context, syncID string) (PltMessage, error) {
	row := q.db.QueryRow(ctx, findBySyncID, syncID)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const findChangesSince = `-- name: FindChangesSince :many
SELECT id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
FROM plt_messages
WHERE updated_at_epoch_ms > $1
ORDER BY updated_at_epoch_ms ASC
`

func (q *Queries) FindChangesSince(ctx context.Context, updatedAtEpochMs int64) ([]PltMessage, error) {
	rows, err := q.db.Query(ctx, findChangesSince, updatedAtEpochMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltMessage{}
	for rows.Next() {
		var i PltMessage
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAtEpochMs,
			&i.Deleted,
			&i.Dirty,
			&i.DeletedAt,
			&i.Version,
			&i.SyncConflict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirtyMessages = `-- name: ListDirtyMessages :many
SELECT id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
FROM plt_messages
WHERE dirty = true AND deleted = false
ORDER BY updated_at_epoch_ms ASC
`

func (q *Queries) ListDirtyMessages(ctx context.Context) ([]PltMessage, error) {
	rows, err := q.db.Query(ctx, listDirtyMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltMessage{}
	for rows.Next() {
		var i PltMessage
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAtEpochMs,
			&i.Deleted,
			&i.Dirty,
			&i.DeletedAt,
			&i.Version,
			&i.SyncConflict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
FROM plt_messages
WHERE deleted = false
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMessagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]PltMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltMessage{}
	for rows.Next() {
		var i PltMessage
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAtEpochMs,
			&i.Deleted,
			&i.Dirty,
			&i.DeletedAt,
			&i.Version,
			&i.SyncConflict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCleanMessages = `-- name: MarkCleanMessages :exec
UPDATE plt_messages SET dirty = false WHERE dirty = true
`

func (q *Queries) MarkCleanMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markCleanMessages)
	return err
}

const markConflictMessage = `-- name: MarkConflictMessage :one
UPDATE plt_messages
SET sync_conflict = $2, version = version + 1
WHERE sync_id = $1
RETURNING id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
`

type MarkConflictMessageParams struct {
	SyncID       string  `json:"sync_id"`
	SyncConflict *string `json:"sync_conflict"`
}

func (q *Queries) MarkConflictMessage(ctx context.Context, arg MarkConflictMessageParams) (PltMessage, error) {
	row := q.db.QueryRow(ctx, markConflictMessage, arg.SyncID, arg.SyncConflict)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const resolveConflictMessage = `-- name: ResolveConflictMessage :one
UPDATE plt_messages
SET sync_conflict = NULL, version = version + 1
WHERE sync_id = $1
RETURNING id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
`

func (q *Queries) ResolveConflictMessage(ctx context.Context, syncID string) (PltMessage, error) {
	row := q.db.QueryRow(ctx, resolveConflictMessage, syncID)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const restoreMessage = `-- name: RestoreMessage :one
UPDATE plt_messages
SET deleted = false, deleted_at = NULL, dirty = true, version = version + 1
WHERE sync_id = $1
RETURNING id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
`

func (q *Queries) RestoreMessage(ctx context.Context, syncID string) (PltMessage, error) {
	row := q.db.QueryRow(ctx, restoreMessage, syncID)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE plt_messages
SET deleted = true, deleted_at = CURRENT_TIMESTAMP, dirty = true, version = version + 1
WHERE sync_id = $1
RETURNING id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, syncID string) (PltMessage, error) {
	row := q.db.QueryRow(ctx, softDeleteMessage, syncID)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE plt_messages
SET author = $2, content = $3, updated_at_epoch_ms = $4, dirty = $5, version = version + 1
WHERE sync_id = $1 AND version = $6
RETURNING id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
`

type UpdateMessageParams struct {
	SyncID           string `json:"sync_id"`
	Author           string `json:"author"`
	Content          string `json:"content"`
	UpdatedAtEpochMs int64  `json:"updated_at_epoch_ms"`
	Dirty            bool   `json:"dirty"`
	Version          int64  `json:"version"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (PltMessage, error) {
	row := q.db.QueryRow(ctx, updateMessage,
		arg.SyncID,
		arg.Author,
		arg.Content,
		arg.UpdatedAtEpochMs,
		arg.Dirty,
		arg.Version,
	)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}

const upsertSyncedMessage = `-- name: UpsertSyncedMessage :one
INSERT INTO plt_messages (sync_id, author, content, updated_at_epoch_ms, dirty, deleted, version)
VALUES ($1, $2, $3, $4, false, $5, 1)
ON CONFLICT (sync_id) DO UPDATE SET
    author = EXCLUDED.author,
    content = EXCLUDED.content,
    updated_at_epoch_ms = EXCLUDED.updated_at_epoch_ms,
    dirty = false,
    deleted = EXCLUDED.deleted,
    version = plt_messages.version + 1,
    sync_conflict = NULL
RETURNING id, sync_id, author, content, created_at, updated_at_epoch_ms, deleted, dirty, deleted_at, version, sync_conflict
`

type UpsertSyncedMessageParams struct {
	SyncID           string `json:"sync_id"`
	Author           string `json:"author"`
	Content          string `json:"content"`
	UpdatedAtEpochMs int64  `json:"updated_at_epoch_ms"`
	Deleted          bool   `json:"deleted"`
}

func (q *Queries) UpsertSyncedMessage(ctx context.Context, arg UpsertSyncedMessageParams) (PltMessage, error) {
	row := q.db.QueryRow(ctx, upsertSyncedMessage,
		arg.SyncID,
		arg.Author,
		arg.Content,
		arg.UpdatedAtEpochMs,
		arg.Deleted,
	)
	var i PltMessage
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAtEpochMs,
		&i.Deleted,
		&i.Dirty,
		&i.DeletedAt,
		&i.Version,
		&i.SyncConflict,
	)
	return i, err
}
