// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PltApiKey struct {
	ID         int64            `json:"id"`
	UserID     uuid.UUID        `json:"user_id"`
	KeyHash    string           `json:"key_hash"`
	KeyPrefix  string           `json:"key_prefix"`
	Name       string           `json:"name"`
	Enabled    bool             `json:"enabled"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
}

type PltAuditLog struct {
	ID             int64            `json:"id"`
	ActorID        pgtype.UUID      `json:"actor_id"`
	ActorUsername  *string          `json:"actor_username"`
	TargetID       pgtype.UUID      `json:"target_id"`
	TargetUsername *string          `json:"target_username"`
	Action         string           `json:"action"`
	Detail         *string          `json:"detail"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type PltContact struct {
	ID               int64            `json:"id"`
	SyncID           string           `json:"sync_id"`
	Name             string           `json:"name"`
	Company          *string          `json:"company"`
	CompanyAddress   *string          `json:"company_address"`
	Department       *string          `json:"department"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAtEpochMs int64            `json:"updated_at_epoch_ms"`
	Deleted          bool             `json:"deleted"`
	Dirty            bool             `json:"dirty"`
	Version          int64            `json:"version"`
	SyncConflict     *string          `json:"sync_conflict"`
}

type PltContactEmail struct {
	ContactID int64  `json:"contact_id"`
	Email     string `json:"email"`
}

type PltContactPhone struct {
	ContactID int64  `json:"contact_id"`
	Phone     string `json:"phone"`
}

type PltContactSocial struct {
	ContactID   int64  `json:"contact_id"`
	SocialMedia string `json:"social_media"`
}

type PltDeviceToken struct {
	ID        int64            `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Platform  string           `json:"platform"`
	Token     string           `json:"token"`
	AppBundle *string          `json:"app_bundle"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	LastSeen  pgtype.Timestamp `json:"last_seen"`
}

type PltMessage struct {
	ID               int64            `json:"id"`
	SyncID           string           `json:"sync_id"`
	Author           string           `json:"author"`
	Content          string           `json:"content"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAtEpochMs int64            `json:"updated_at_epoch_ms"`
	Deleted          bool             `json:"deleted"`
	Dirty            bool             `json:"dirty"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
	Version          int64            `json:"version"`
	SyncConflict     *string          `json:"sync_conflict"`
}

type PltNotification struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Title     string           `json:"title"`
	Body      string           `json:"body"`
	Type      string           `json:"type"`
	ReadAt    pgtype.Timestamp `json:"read_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type PltOauthConnection struct {
	ID        int64            `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Provider  string           `json:"provider"`
	Subject   string           `json:"subject"`
	Email     *string          `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type PltOutbox struct {
	ID          uuid.UUID        `json:"id"`
	PayloadType string           `json:"payload_type"`
	Payload     string           `json:"payload"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	RetryCount  *int32           `json:"retry_count"`
	LastError   *string          `json:"last_error"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type PltPasswordResetToken struct {
	ID        int64            `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Used      bool             `json:"used"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type PltSession struct {
	ID        int64            `json:"id"`
	TokenHash string           `json:"token_hash"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type PltSyncState struct {
	StateKey   string `json:"state_key"`
	StateValue int64  `json:"state_value"`
}

type PltUser struct {
	ID                        uuid.UUID          `json:"id"`
	Username                  string             `json:"username"`
	Email                     string             `json:"email"`
	PasswordHash              string             `json:"password_hash"`
	Role                      string             `json:"role"`
	Enabled                   bool               `json:"enabled"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	LastActivityAt            pgtype.Timestamp   `json:"last_activity_at"`
	AvatarUrl                 *string            `json:"avatar_url"`
	EmailNotificationsEnabled bool               `json:"email_notifications_enabled"`
	PushNotificationsEnabled  bool               `json:"push_notifications_enabled"`
	Language                  *string            `json:"language"`
	Theme                     *string            `json:"theme"`
	Layout                    *string            `json:"layout"`
}
