// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_connections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteOAuthConnection = `-- name: DeleteOAuthConnection :execrows
DELETE FROM plt_oauth_connections WHERE id = $1 AND user_id = $2
`

type DeleteOAuthConnectionParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteOAuthConnection(ctx context.Context, arg DeleteOAuthConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthConnection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOAuthByProviderSubject = `-- name: FindOAuthByProviderSubject :one
SELECT id, user_id, provider, subject, email, created_at
FROM plt_oauth_connections
WHERE provider = $1 AND subject = $2
`

type FindOAuthByProviderSubjectParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) FindOAuthByProviderSubject(ctx context.Context, arg FindOAuthByProviderSubjectParams) (PltOauthConnection, error) {
	row := q.db.QueryRow(ctx, findOAuthByProviderSubject, arg.Provider, arg.Subject)
	var i PltOauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const findOAuthByUserID = `-- name: FindOAuthByUserID :many
SELECT id, user_id, provider, subject, email, created_at
FROM plt_oauth_connections
WHERE user_id = $1
`

func (q *Queries) FindOAuthByUserID(ctx context.Context, userID uuid.UUID) ([]PltOauthConnection, error) {
	rows, err := q.db.Query(ctx, findOAuthByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltOauthConnection{}
	for rows.Next() {
		var i PltOauthConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOAuthConnection = `-- name: SaveOAuthConnection :one
INSERT INTO plt_oauth_connections (user_id, provider, subject, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, subject, email, created_at
`

type SaveOAuthConnectionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
	Subject  string    `json:"subject"`
	Email    *string   `json:"email"`
}

func (q *Queries) SaveOAuthConnection(ctx context.Context, arg SaveOAuthConnectionParams) (PltOauthConnection, error) {
	row := q.db.QueryRow(ctx, saveOAuthConnection,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	var i PltOauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
