// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingOutbox = `-- name: ClaimPendingOutbox :many
UPDATE plt_outbox
SET status = 'PROCESSING', retry_count = retry_count + 1
WHERE id IN (
    SELECT id FROM plt_outbox
    WHERE status = 'PENDING' OR (status = 'PROCESSING' AND retry_count < 5)
    ORDER BY created_at ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, payload_type, payload, status, created_at, processed_at, retry_count, last_error
`

type ClaimPendingOutboxRow struct {
	ID          uuid.UUID        `json:"id"`
	PayloadType string           `json:"payload_type"`
	Payload     string           `json:"payload"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	RetryCount  *int32           `json:"retry_count"`
	LastError   *string          `json:"last_error"`
}

func (q *Queries) ClaimPendingOutbox(ctx context.Context, limit int32) ([]ClaimPendingOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingOutboxRow{}
	for rows.Next() {
		var i ClaimPendingOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.PayloadType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.RetryCount,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutboxStats = `-- name: GetOutboxStats :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'PENDING') AS pending,
    COUNT(*) FILTER (WHERE status = 'PROCESSED') AS processed,
    COUNT(*) FILTER (WHERE status = 'FAILED') AS failed
FROM plt_outbox
`

type GetOutboxStatsRow struct {
	Total     int64 `json:"total"`
	Pending   int64 `json:"pending"`
	Processed int64 `json:"processed"`
	Failed    int64 `json:"failed"`
}

func (q *Queries) GetOutboxStats(ctx context.Context) (GetOutboxStatsRow, error) {
	row := q.db.QueryRow(ctx, getOutboxStats)
	var i GetOutboxStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Processed,
		&i.Failed,
	)
	return i, err
}

const listDeadLetterOutbox = `-- name: ListDeadLetterOutbox :many
SELECT id, payload_type, payload, status, created_at, processed_at, retry_count, last_error
FROM plt_outbox
WHERE status = 'DEAD_LETTER'
ORDER BY created_at ASC
LIMIT $1
`

type ListDeadLetterOutboxRow struct {
	ID          uuid.UUID        `json:"id"`
	PayloadType string           `json:"payload_type"`
	Payload     string           `json:"payload"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	RetryCount  *int32           `json:"retry_count"`
	LastError   *string          `json:"last_error"`
}

func (q *Queries) ListDeadLetterOutbox(ctx context.Context, limit int32) ([]ListDeadLetterOutboxRow, error) {
	rows, err := q.db.Query(ctx, listDeadLetterOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeadLetterOutboxRow{}
	for rows.Next() {
		var i ListDeadLetterOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.PayloadType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.RetryCount,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedOutbox = `-- name: ListFailedOutbox :many
SELECT id, payload_type, payload, status, created_at, processed_at, retry_count, last_error
FROM plt_outbox
WHERE status = 'FAILED'
ORDER BY created_at ASC
LIMIT $1
`

type ListFailedOutboxRow struct {
	ID          uuid.UUID        `json:"id"`
	PayloadType string           `json:"payload_type"`
	Payload     string           `json:"payload"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	RetryCount  *int32           `json:"retry_count"`
	LastError   *string          `json:"last_error"`
}

func (q *Queries) ListFailedOutbox(ctx context.Context, limit int32) ([]ListFailedOutboxRow, error) {
	rows, err := q.db.Query(ctx, listFailedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailedOutboxRow{}
	for rows.Next() {
		var i ListFailedOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.PayloadType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.RetryCount,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutbox = `-- name: ListPendingOutbox :many
SELECT id, payload_type, payload, status, created_at, processed_at, retry_count, last_error
FROM plt_outbox
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1
`

type ListPendingOutboxRow struct {
	ID          uuid.UUID        `json:"id"`
	PayloadType string           `json:"payload_type"`
	Payload     string           `json:"payload"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	RetryCount  *int32           `json:"retry_count"`
	LastError   *string          `json:"last_error"`
}

func (q *Queries) ListPendingOutbox(ctx context.Context, limit int32) ([]ListPendingOutboxRow, error) {
	rows, err := q.db.Query(ctx, listPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingOutboxRow{}
	for rows.Next() {
		var i ListPendingOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.PayloadType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.RetryCount,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :one
UPDATE plt_outbox
SET status = 'FAILED', last_error = $2, retry_count = retry_count + 1
WHERE id = $1
RETURNING id, payload_type, payload, status, created_at, processed_at, retry_count, last_error
`

type MarkOutboxFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
}

type MarkOutboxFailedRow struct {
	ID          uuid.UUID        `json:"id"`
	PayloadType string           `json:"payload_type"`
	Payload     string           `json:"payload"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	RetryCount  *int32           `json:"retry_count"`
	LastError   *string          `json:"last_error"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (MarkOutboxFailedRow, error) {
	row := q.db.QueryRow(ctx, markOutboxFailed, arg.ID, arg.LastError)
	var i MarkOutboxFailedRow
	err := row.Scan(
		&i.ID,
		&i.PayloadType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.RetryCount,
		&i.LastError,
	)
	return i, err
}

const markOutboxProcessed = `-- name: MarkOutboxProcessed :one
UPDATE plt_outbox
SET status = 'PROCESSED', processed_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, payload_type, payload, status, created_at, processed_at, retry_count, last_error
`

type MarkOutboxProcessedRow struct {
	ID          uuid.UUID        `json:"id"`
	PayloadType string           `json:"payload_type"`
	Payload     string           `json:"payload"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	RetryCount  *int32           `json:"retry_count"`
	LastError   *string          `json:"last_error"`
}

func (q *Queries) MarkOutboxProcessed(ctx context.Context, id uuid.UUID) (MarkOutboxProcessedRow, error) {
	row := q.db.QueryRow(ctx, markOutboxProcessed, id)
	var i MarkOutboxProcessedRow
	err := row.Scan(
		&i.ID,
		&i.PayloadType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.RetryCount,
		&i.LastError,
	)
	return i, err
}

const saveOutbox = `-- name: SaveOutbox :exec
INSERT INTO plt_outbox (id, payload_type, payload, status)
VALUES ($1, $2, $3, $4)
`

type SaveOutboxParams struct {
	ID          uuid.UUID `json:"id"`
	PayloadType string    `json:"payload_type"`
	Payload     string    `json:"payload"`
	Status      string    `json:"status"`
}

func (q *Queries) SaveOutbox(ctx context.Context, arg SaveOutboxParams) error {
	_, err := q.db.Exec(ctx, saveOutbox,
		arg.ID,
		arg.PayloadType,
		arg.Payload,
		arg.Status,
	)
	return err
}

const updateOutboxStatus = `-- name: UpdateOutboxStatus :one
UPDATE plt_outbox
SET status = $2, last_error = $3
WHERE id = $1
RETURNING id, payload_type, payload, status, created_at, processed_at, retry_count, last_error
`

type UpdateOutboxStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	LastError *string   `json:"last_error"`
}

type UpdateOutboxStatusRow struct {
	ID          uuid.UUID        `json:"id"`
	PayloadType string           `json:"payload_type"`
	Payload     string           `json:"payload"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	RetryCount  *int32           `json:"retry_count"`
	LastError   *string          `json:"last_error"`
}

func (q *Queries) UpdateOutboxStatus(ctx context.Context, arg UpdateOutboxStatusParams) (UpdateOutboxStatusRow, error) {
	row := q.db.QueryRow(ctx, updateOutboxStatus, arg.ID, arg.Status, arg.LastError)
	var i UpdateOutboxStatusRow
	err := row.Scan(
		&i.ID,
		&i.PayloadType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.RetryCount,
		&i.LastError,
	)
	return i, err
}
