// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordReset = `-- name: ConsumePasswordReset :one
WITH consumed AS (
    UPDATE plt_password_reset_tokens
    SET used = true
    WHERE token = $1
      AND used = false
      AND expires_at > CURRENT_TIMESTAMP
    RETURNING user_id
)
UPDATE plt_users
SET password_hash = $2
FROM consumed
WHERE plt_users.id = consumed.user_id
RETURNING plt_users.id, username, email, password_hash, role, enabled, created_at,
          last_activity_at, avatar_url, email_notifications_enabled,
          push_notifications_enabled, language, theme, layout
`

type ConsumePasswordResetParams struct {
	Token        string `json:"token"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) ConsumePasswordReset(ctx context.Context, arg ConsumePasswordResetParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, consumePasswordReset, arg.Token, arg.PasswordHash)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
	)
	return i, err
}

const savePasswordResetToken = `-- name: SavePasswordResetToken :one
INSERT INTO plt_password_reset_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, used, created_at
`

type SavePasswordResetTokenParams struct {
	UserID    uuid.UUID        `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) SavePasswordResetToken(ctx context.Context, arg SavePasswordResetTokenParams) (PltPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, savePasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PltPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}
