// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findPasswordResetByToken = `-- name: FindPasswordResetByToken :one
SELECT id, user_id, token, expires_at, used, created_at
FROM plt_password_reset_tokens
WHERE token = $1
`

func (q *Queries) FindPasswordResetByToken(ctx context.Context, token string) (PltPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, findPasswordResetByToken, token)
	var i PltPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :one
UPDATE plt_password_reset_tokens
SET used = true
WHERE token = $1
RETURNING id, user_id, token, expires_at, used, created_at
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, token string) (PltPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, markPasswordResetUsed, token)
	var i PltPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const savePasswordResetToken = `-- name: SavePasswordResetToken :one
INSERT INTO plt_password_reset_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, used, created_at
`

type SavePasswordResetTokenParams struct {
	UserID    uuid.UUID        `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) SavePasswordResetToken(ctx context.Context, arg SavePasswordResetTokenParams) (PltPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, savePasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PltPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}
