// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: polls.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const castPollVote = `-- name: CastPollVote :execrows
INSERT INTO plt_poll_votes (poll_id, option_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (poll_id, option_id, user_id) DO NOTHING
`

type CastPollVoteParams struct {
	PollID   int64     `json:"poll_id"`
	OptionID int64     `json:"option_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CastPollVote(ctx context.Context, arg CastPollVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, castPollVote, arg.PollID, arg.OptionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closePoll = `-- name: ClosePoll :execrows
UPDATE plt_polls
SET closed_at = COALESCE(closed_at, NOW()), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClosePoll(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, closePoll, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPoll = `-- name: CreatePoll :one
INSERT INTO plt_polls (sync_id, creator_id, question, multi_choice, deadline)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, sync_id, creator_id, question, multi_choice, closed_at, deadline, created_at, updated_at
`

type CreatePollParams struct {
	SyncID      string             `json:"sync_id"`
	CreatorID   uuid.UUID          `json:"creator_id"`
	Question    string             `json:"question"`
	MultiChoice bool               `json:"multi_choice"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (PltPoll, error) {
	row := q.db.QueryRow(ctx, createPoll,
		arg.SyncID,
		arg.CreatorID,
		arg.Question,
		arg.MultiChoice,
		arg.Deadline,
	)
	var i PltPoll
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.CreatorID,
		&i.Question,
		&i.MultiChoice,
		&i.ClosedAt,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPollOption = `-- name: CreatePollOption :one
INSERT INTO plt_poll_options (poll_id, position, option_text)
VALUES ($1, $2, $3)
RETURNING id, poll_id, position, option_text
`

type CreatePollOptionParams struct {
	PollID     int64  `json:"poll_id"`
	Position   int16  `json:"position"`
	OptionText string `json:"option_text"`
}

func (q *Queries) CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PltPollOption, error) {
	row := q.db.QueryRow(ctx, createPollOption, arg.PollID, arg.Position, arg.OptionText)
	var i PltPollOption
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Position,
		&i.OptionText,
	)
	return i, err
}

const deletePoll = `-- name: DeletePoll :execrows
DELETE FROM plt_polls
WHERE id = $1
`

func (q *Queries) DeletePoll(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePoll, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPollBySyncID = `-- name: FindPollBySyncID :one
SELECT id, sync_id, creator_id, question, multi_choice, closed_at, deadline, created_at, updated_at
FROM plt_polls
WHERE sync_id = $1
`

func (q *Queries) FindPollBySyncID(ctx context.Context, syncID string) (PltPoll, error) {
	row := q.db.QueryRow(ctx, findPollBySyncID, syncID)
	var i PltPoll
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.CreatorID,
		&i.Question,
		&i.MultiChoice,
		&i.ClosedAt,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPollOption = `-- name: FindPollOption :one
SELECT id, poll_id, position, option_text
FROM plt_poll_options
WHERE poll_id = $1 AND id = $2
`

type FindPollOptionParams struct {
	PollID int64 `json:"poll_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) FindPollOption(ctx context.Context, arg FindPollOptionParams) (PltPollOption, error) {
	row := q.db.QueryRow(ctx, findPollOption, arg.PollID, arg.ID)
	var i PltPollOption
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Position,
		&i.OptionText,
	)
	return i, err
}

const listOpenPolls = `-- name: ListOpenPolls :many
SELECT p.id, p.sync_id, p.creator_id, p.question, p.multi_choice, p.closed_at, p.deadline, p.created_at, p.updated_at,
       (SELECT COUNT(*)::INTEGER FROM plt_poll_votes v WHERE v.poll_id = p.id) AS total_votes
FROM plt_polls p
WHERE p.closed_at IS NULL AND (p.deadline IS NULL OR p.deadline > NOW())
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListOpenPollsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOpenPollsRow struct {
	ID          int64              `json:"id"`
	SyncID      string             `json:"sync_id"`
	CreatorID   uuid.UUID          `json:"creator_id"`
	Question    string             `json:"question"`
	MultiChoice bool               `json:"multi_choice"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	TotalVotes  int32              `json:"total_votes"`
}

func (q *Queries) ListOpenPolls(ctx context.Context, arg ListOpenPollsParams) ([]ListOpenPollsRow, error) {
	rows, err := q.db.Query(ctx, listOpenPolls, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenPollsRow{}
	for rows.Next() {
		var i ListOpenPollsRow
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.CreatorID,
			&i.Question,
			&i.MultiChoice,
			&i.ClosedAt,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalVotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollOptions = `-- name: ListPollOptions :many
SELECT id, poll_id, position, option_text
FROM plt_poll_options
WHERE poll_id = $1
ORDER BY position
`

func (q *Queries) ListPollOptions(ctx context.Context, pollID int64) ([]PltPollOption, error) {
	rows, err := q.db.Query(ctx, listPollOptions, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltPollOption{}
	for rows.Next() {
		var i PltPollOption
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Position,
			&i.OptionText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollVoteCounts = `-- name: ListPollVoteCounts :many
SELECT option_id, COUNT(*)::INTEGER AS vote_count
FROM plt_poll_votes
WHERE poll_id = $1
GROUP BY option_id
`

type ListPollVoteCountsRow struct {
	OptionID  int64 `json:"option_id"`
	VoteCount int32 `json:"vote_count"`
}

func (q *Queries) ListPollVoteCounts(ctx context.Context, pollID int64) ([]ListPollVoteCountsRow, error) {
	rows, err := q.db.Query(ctx, listPollVoteCounts, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollVoteCountsRow{}
	for rows.Next() {
		var i ListPollVoteCountsRow
		if err := rows.Scan(&i.OptionID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPollVotes = `-- name: ListUserPollVotes :many
SELECT option_id
FROM plt_poll_votes
WHERE poll_id = $1 AND user_id = $2
ORDER BY option_id
`

type ListUserPollVotesParams struct {
	PollID int64     `json:"poll_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListUserPollVotes(ctx context.Context, arg ListUserPollVotesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserPollVotes, arg.PollID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var option_id int64
		if err := rows.Scan(&option_id); err != nil {
			return nil, err
		}
		items = append(items, option_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPollBySyncID = `-- name: LockPollBySyncID :one
SELECT id, sync_id, creator_id, question, multi_choice, closed_at, deadline, created_at, updated_at
FROM plt_polls
WHERE sync_id = $1
FOR UPDATE
`

func (q *Queries) LockPollBySyncID(ctx context.Context, syncID string) (PltPoll, error) {
	row := q.db.QueryRow(ctx, lockPollBySyncID, syncID)
	var i PltPoll
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.CreatorID,
		&i.Question,
		&i.MultiChoice,
		&i.ClosedAt,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removePollVote = `-- name: RemovePollVote :execrows
DELETE FROM plt_poll_votes
WHERE poll_id = $1 AND option_id = $2 AND user_id = $3
`

type RemovePollVoteParams struct {
	PollID   int64     `json:"poll_id"`
	OptionID int64     `json:"option_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) RemovePollVote(ctx context.Context, arg RemovePollVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, removePollVote, arg.PollID, arg.OptionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
