// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CastPollVote(ctx context.Context, arg CastPollVoteParams) (int64, error)
	ClaimPendingOutbox(ctx context.Context, limit int32) ([]ClaimPendingOutboxRow, error)
	ClosePoll(ctx context.Context, id int64) (int64, error)
	CountAllAudit(ctx context.Context) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountContacts(ctx context.Context) (int64, error)
	CountDirtyMessages(ctx context.Context) (int64, error)
	CountMessages(ctx context.Context) (int64, error)
	CountMessagesByYear(ctx context.Context, updatedAtEpochMs int64) (int64, error)
	CountSearchContacts(ctx context.Context, dollar_1 string) (int64, error)
	CountSearchMessages(ctx context.Context, dollar_1 string) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (PltApiKey, error)
	CreateLocalContact(ctx context.Context, arg CreateLocalContactParams) (PltContact, error)
	CreateLocalMessage(ctx context.Context, arg CreateLocalMessageParams) (PltMessage, error)
	CreateMessageVote(ctx context.Context, arg CreateMessageVoteParams) (PltMessageVote, error)
	CreatePoll(ctx context.Context, arg CreatePollParams) (PltPoll, error)
	CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PltPollOption, error)
	CreateServerContact(ctx context.Context, arg CreateServerContactParams) (PltContact, error)
	CreateServerMessage(ctx context.Context, arg CreateServerMessageParams) (PltMessage, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (PltSession, error)
	CreateTOTPChallenge(ctx context.Context, arg CreateTOTPChallengeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (PltUser, error)
	DeleteAllDeviceTokensForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) (int64, error)
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteExpiredTOTPChallenges(ctx context.Context) (int64, error)
	DeleteMessageVote(ctx context.Context, arg DeleteMessageVoteParams) (int64, error)
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error)
	DeleteOAuthConnection(ctx context.Context, arg DeleteOAuthConnectionParams) (int64, error)
	DeletePoll(ctx context.Context, id int64) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteTOTPChallenge(ctx context.Context, tokenHash string) (int64, error)
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	DisableUserTOTP(ctx context.Context, id uuid.UUID) error
	EnableUserTOTP(ctx context.Context, arg EnableUserTOTPParams) error
	FindAllUsers(ctx context.Context) ([]PltUser, error)
	FindApiKeyByHash(ctx context.Context, keyHash string) (PltApiKey, error)
	FindApiKeysByUserID(ctx context.Context, userID uuid.UUID) ([]PltApiKey, error)
	FindAuditPage(ctx context.Context, arg FindAuditPageParams) ([]PltAuditLog, error)
	FindBySyncID(ctx context.Context, syncID string) (PltMessage, error)
	FindChangesSince(ctx context.Context, updatedAtEpochMs int64) ([]PltMessage, error)
	FindContactBySyncID(ctx context.Context, syncID string) (PltContact, error)
	FindContactChangesSince(ctx context.Context, updatedAtEpochMs int64) ([]PltContact, error)
	FindDeviceTokensByUserID(ctx context.Context, userID uuid.UUID) ([]PltDeviceToken, error)
	FindMessageVote(ctx context.Context, arg FindMessageVoteParams) (PltMessageVote, error)
	FindNotificationsByUserID(ctx context.Context, arg FindNotificationsByUserIDParams) ([]PltNotification, error)
	FindOAuthByProviderSubject(ctx context.Context, arg FindOAuthByProviderSubjectParams) (PltOauthConnection, error)
	FindOAuthByUserID(ctx context.Context, userID uuid.UUID) ([]PltOauthConnection, error)
	FindPasswordResetByToken(ctx context.Context, token string) (PltPasswordResetToken, error)
	FindPollBySyncID(ctx context.Context, syncID string) (PltPoll, error)
	FindPollOption(ctx context.Context, arg FindPollOptionParams) (PltPollOption, error)
	FindRecentAudit(ctx context.Context, limit int32) ([]PltAuditLog, error)
	FindSessionByTokenHash(ctx context.Context, tokenHash string) (PltSession, error)
	FindSessionByTokenHashIncludingExpired(ctx context.Context, tokenHash string) (PltSession, error)
	FindUserByEmail(ctx context.Context, email string) (PltUser, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (PltUser, error)
	FindUserByUsername(ctx context.Context, username string) (PltUser, error)
	FindUserPage(ctx context.Context, arg FindUserPageParams) ([]PltUser, error)
	GetOutboxStats(ctx context.Context) (GetOutboxStatsRow, error)
	GetSyncState(ctx context.Context, stateKey string) (PltSyncState, error)
	IncrementFailedLoginAttempts(ctx context.Context, id uuid.UUID) (int32, error)
	IncrementFailedTOTPAttempts(ctx context.Context, id uuid.UUID) (int32, error)
	InsertContactEmail(ctx context.Context, arg InsertContactEmailParams) error
	InsertContactPhone(ctx context.Context, arg InsertContactPhoneParams) error
	InsertContactSocial(ctx context.Context, arg InsertContactSocialParams) error
	ListContactEmails(ctx context.Context, contactID int64) ([]string, error)
	ListContactEmailsBatch(ctx context.Context, dollar_1 []int64) ([]PltContactEmail, error)
	ListContactPhones(ctx context.Context, contactID int64) ([]string, error)
	ListContactPhonesBatch(ctx context.Context, dollar_1 []int64) ([]PltContactPhone, error)
	ListContactSocials(ctx context.Context, contactID int64) ([]string, error)
	ListContactSocialsBatch(ctx context.Context, dollar_1 []int64) ([]PltContactSocial, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]PltContact, error)
	ListDeadLetterOutbox(ctx context.Context, limit int32) ([]ListDeadLetterOutboxRow, error)
	ListDirtyContacts(ctx context.Context) ([]PltContact, error)
	ListDirtyMessages(ctx context.Context) ([]PltMessage, error)
	ListFailedOutbox(ctx context.Context, limit int32) ([]ListFailedOutboxRow, error)
	ListMessageVoteCounts(ctx context.Context, messageSyncIds []string) ([]ListMessageVoteCountsRow, error)
	// Distinct calendar years (descending) for which non-deleted messages exist.
	// Used to populate the year filter on the messages page.
	ListMessageYears(ctx context.Context) ([]int32, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]PltMessage, error)
	// Returns one page of non-deleted messages whose updated_at falls in the given
	// calendar year (interpreted in the database session time zone). updated_at is
	// stored as epoch milliseconds, so it is converted to a timestamp with
	// TO_TIMESTAMP(epoch / 1000.0) before EXTRACT.
	ListMessagesByYear(ctx context.Context, arg ListMessagesByYearParams) ([]PltMessage, error)
	ListOpenPolls(ctx context.Context, arg ListOpenPollsParams) ([]ListOpenPollsRow, error)
	ListPendingOutbox(ctx context.Context, limit int32) ([]ListPendingOutboxRow, error)
	ListPollOptions(ctx context.Context, pollID int64) ([]PltPollOption, error)
	ListPollVoteCounts(ctx context.Context, pollID int64) ([]ListPollVoteCountsRow, error)
	ListSessionsForUser(ctx context.Context, userID uuid.UUID) ([]ListSessionsForUserRow, error)
	ListUserMessageVotes(ctx context.Context, arg ListUserMessageVotesParams) ([]ListUserMessageVotesRow, error)
	ListUserPollVotes(ctx context.Context, arg ListUserPollVotesParams) ([]int64, error)
	LockMessageForVote(ctx context.Context, syncID string) (int64, error)
	LockPollBySyncID(ctx context.Context, syncID string) (PltPoll, error)
	LockUserUntil(ctx context.Context, arg LockUserUntilParams) error
	LogAudit(ctx context.Context, arg LogAuditParams) (PltAuditLog, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error)
	MarkCleanContacts(ctx context.Context) error
	MarkCleanMessages(ctx context.Context) error
	MarkConflictContact(ctx context.Context, arg MarkConflictContactParams) (PltContact, error)
	MarkConflictMessage(ctx context.Context, arg MarkConflictMessageParams) (PltMessage, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (PltNotification, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (MarkOutboxFailedRow, error)
	MarkOutboxProcessed(ctx context.Context, id uuid.UUID) (MarkOutboxProcessedRow, error)
	MarkPasswordResetUsed(ctx context.Context, token string) (PltPasswordResetToken, error)
	RemovePollVote(ctx context.Context, arg RemovePollVoteParams) (int64, error)
	ReplaceTOTPBackupCodes(ctx context.Context, arg ReplaceTOTPBackupCodesParams) (int64, error)
	ResetFailedTOTPAttempts(ctx context.Context, id uuid.UUID) error
	ResetLoginFailures(ctx context.Context, id uuid.UUID) error
	ResolveConflictContact(ctx context.Context, syncID string) (PltContact, error)
	ResolveConflictMessage(ctx context.Context, syncID string) (PltMessage, error)
	RestoreContact(ctx context.Context, syncID string) (PltContact, error)
	RestoreMessage(ctx context.Context, syncID string) (PltMessage, error)
	SaveNotification(ctx context.Context, arg SaveNotificationParams) (PltNotification, error)
	SaveOAuthConnection(ctx context.Context, arg SaveOAuthConnectionParams) (PltOauthConnection, error)
	SaveOutbox(ctx context.Context, arg SaveOutboxParams) error
	SavePasswordResetToken(ctx context.Context, arg SavePasswordResetTokenParams) (PltPasswordResetToken, error)
	// Returns one page of non-deleted contacts whose name or company match the
	// query (case-insensitive ILIKE). Mirrors SearchMessages. company is nullable,
	// so COALESCE protects the ILIKE from NULL operands.
	SearchContacts(ctx context.Context, arg SearchContactsParams) ([]PltContact, error)
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]PltMessage, error)
	SeedAdminUser(ctx context.Context, arg SeedAdminUserParams) (PltUser, error)
	SetContactEmails(ctx context.Context, contactID int64) error
	SetContactPhones(ctx context.Context, contactID int64) error
	SetContactSocials(ctx context.Context, contactID int64) error
	SetSyncState(ctx context.Context, arg SetSyncStateParams) error
	SoftDeleteContact(ctx context.Context, syncID string) (PltContact, error)
	SoftDeleteMessage(ctx context.Context, syncID string) (PltMessage, error)
	TakeTOTPChallengeAttempt(ctx context.Context, arg TakeTOTPChallengeAttemptParams) (PltTotpChallenge, error)
	UpdateApiKeyLastUsed(ctx context.Context, id int64) error
	UpdateAvatarURL(ctx context.Context, arg UpdateAvatarURLParams) (PltUser, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (PltContact, error)
	UpdateLastActivity(ctx context.Context, id uuid.UUID) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (PltMessage, error)
	UpdateMessageVote(ctx context.Context, arg UpdateMessageVoteParams) (int64, error)
	UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (PltUser, error)
	UpdateOutboxStatus(ctx context.Context, arg UpdateOutboxStatusParams) (UpdateOutboxStatusRow, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (PltUser, error)
	UpdateSessionExpiresAt(ctx context.Context, arg UpdateSessionExpiresAtParams) (PltSession, error)
	UpdateUserEnabled(ctx context.Context, arg UpdateUserEnabledParams) (PltUser, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (PltUser, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (PltUser, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (PltDeviceToken, error)
	UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (PltSyncState, error)
	UpsertSyncedContact(ctx context.Context, arg UpsertSyncedContactParams) (PltContact, error)
	UpsertSyncedMessage(ctx context.Context, arg UpsertSyncedMessageParams) (PltMessage, error)
}

var _ Querier = (*Queries)(nil)
