// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO plt_sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token_hash, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	TokenHash string           `json:"token_hash"`
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (PltSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i PltSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM plt_sessions WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM plt_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM plt_sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT id, token_hash, user_id, created_at, expires_at
FROM plt_sessions
WHERE token_hash = $1 AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) FindSessionByTokenHash(ctx context.Context, tokenHash string) (PltSession, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHash, tokenHash)
	var i PltSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findSessionByTokenHashIncludingExpired = `-- name: FindSessionByTokenHashIncludingExpired :one
SELECT id, token_hash, user_id, created_at, expires_at
FROM plt_sessions
WHERE token_hash = $1
`

func (q *Queries) FindSessionByTokenHashIncludingExpired(ctx context.Context, tokenHash string) (PltSession, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHashIncludingExpired, tokenHash)
	var i PltSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT token_hash, user_id, created_at, expires_at
FROM plt_sessions
WHERE user_id = $1 AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

type ListSessionsForUserRow struct {
	TokenHash string           `json:"token_hash"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) ListSessionsForUser(ctx context.Context, userID uuid.UUID) ([]ListSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForUserRow{}
	for rows.Next() {
		var i ListSessionsForUserRow
		if err := rows.Scan(
			&i.TokenHash,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionExpiresAt = `-- name: UpdateSessionExpiresAt :one
UPDATE plt_sessions SET expires_at = $2 WHERE token_hash = $1
RETURNING id, token_hash, user_id, created_at, expires_at
`

type UpdateSessionExpiresAtParams struct {
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) UpdateSessionExpiresAt(ctx context.Context, arg UpdateSessionExpiresAtParams) (PltSession, error) {
	row := q.db.QueryRow(ctx, updateSessionExpiresAt, arg.TokenHash, arg.ExpiresAt)
	var i PltSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
