// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package db

import (
	"context"
)

const getSyncState = `-- name: GetSyncState :one
SELECT state_key, state_value FROM plt_sync_state WHERE state_key = $1
`

func (q *Queries) GetSyncState(ctx context.Context, stateKey string) (PltSyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState, stateKey)
	var i PltSyncState
	err := row.Scan(&i.StateKey, &i.StateValue)
	return i, err
}

const setSyncState = `-- name: SetSyncState :exec
UPDATE plt_sync_state SET state_value = $2 WHERE state_key = $1
`

type SetSyncStateParams struct {
	StateKey   string `json:"state_key"`
	StateValue int64  `json:"state_value"`
}

func (q *Queries) SetSyncState(ctx context.Context, arg SetSyncStateParams) error {
	_, err := q.db.Exec(ctx, setSyncState, arg.StateKey, arg.StateValue)
	return err
}

const upsertSyncState = `-- name: UpsertSyncState :one
INSERT INTO plt_sync_state (state_key, state_value)
VALUES ($1, $2)
ON CONFLICT (state_key) DO UPDATE SET state_value = EXCLUDED.state_value
RETURNING state_key, state_value
`

type UpsertSyncStateParams struct {
	StateKey   string `json:"state_key"`
	StateValue int64  `json:"state_value"`
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (PltSyncState, error) {
	row := q.db.QueryRow(ctx, upsertSyncState, arg.StateKey, arg.StateValue)
	var i PltSyncState
	err := row.Scan(&i.StateKey, &i.StateValue)
	return i, err
}
