// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: totp.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTOTPChallenge = `-- name: CreateTOTPChallenge :exec
INSERT INTO plt_totp_challenges (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateTOTPChallengeParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateTOTPChallenge(ctx context.Context, arg CreateTOTPChallengeParams) error {
	_, err := q.db.Exec(ctx, createTOTPChallenge, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredTOTPChallenges = `-- name: DeleteExpiredTOTPChallenges :execrows
DELETE FROM plt_totp_challenges WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredTOTPChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTOTPChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTOTPChallenge = `-- name: DeleteTOTPChallenge :execrows
DELETE FROM plt_totp_challenges WHERE token_hash = $1
`

func (q *Queries) DeleteTOTPChallenge(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTOTPChallenge, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE plt_users
SET totp_secret = NULL,
    totp_enabled = FALSE,
    totp_backup_codes = NULL,
    failed_totp_attempts = 0
WHERE id = $1
`

func (q *Queries) DisableUserTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableUserTOTP, id)
	return err
}

const enableUserTOTP = `-- name: EnableUserTOTP :exec
UPDATE plt_users
SET totp_secret = $2,
    totp_enabled = TRUE,
    totp_backup_codes = $3,
    failed_totp_attempts = 0
WHERE id = $1
`

type EnableUserTOTPParams struct {
	ID              uuid.UUID `json:"id"`
	TotpSecret      *string   `json:"totp_secret"`
	TotpBackupCodes *string   `json:"totp_backup_codes"`
}

func (q *Queries) EnableUserTOTP(ctx context.Context, arg EnableUserTOTPParams) error {
	_, err := q.db.Exec(ctx, enableUserTOTP, arg.ID, arg.TotpSecret, arg.TotpBackupCodes)
	return err
}

const incrementFailedTOTPAttempts = `-- name: IncrementFailedTOTPAttempts :one
UPDATE plt_users
SET failed_totp_attempts = failed_totp_attempts + 1
WHERE id = $1
RETURNING failed_totp_attempts
`

func (q *Queries) IncrementFailedTOTPAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedTOTPAttempts, id)
	var failed_totp_attempts int32
	err := row.Scan(&failed_totp_attempts)
	return failed_totp_attempts, err
}

const replaceTOTPBackupCodes = `-- name: ReplaceTOTPBackupCodes :execrows
UPDATE plt_users
SET totp_backup_codes = $1
WHERE id = $2
  AND totp_backup_codes = $3
`

type ReplaceTOTPBackupCodesParams struct {
	NewCodes      *string   `json:"new_codes"`
	UserID        uuid.UUID `json:"user_id"`
	ExpectedCodes *string   `json:"expected_codes"`
}

func (q *Queries) ReplaceTOTPBackupCodes(ctx context.Context, arg ReplaceTOTPBackupCodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceTOTPBackupCodes, arg.NewCodes, arg.UserID, arg.ExpectedCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetFailedTOTPAttempts = `-- name: ResetFailedTOTPAttempts :exec
UPDATE plt_users SET failed_totp_attempts = 0 WHERE id = $1
`

func (q *Queries) ResetFailedTOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedTOTPAttempts, id)
	return err
}

const takeTOTPChallengeAttempt = `-- name: TakeTOTPChallengeAttempt :one
UPDATE plt_totp_challenges
SET attempt_count = attempt_count + 1
WHERE token_hash = $1
  AND expires_at > CURRENT_TIMESTAMP
  AND attempt_count < $2
RETURNING token_hash, user_id, attempt_count, expires_at, created_at
`

type TakeTOTPChallengeAttemptParams struct {
	TokenHash    string `json:"token_hash"`
	AttemptCount int32  `json:"attempt_count"`
}

func (q *Queries) TakeTOTPChallengeAttempt(ctx context.Context, arg TakeTOTPChallengeAttemptParams) (PltTotpChallenge, error) {
	row := q.db.QueryRow(ctx, takeTOTPChallengeAttempt, arg.TokenHash, arg.AttemptCount)
	var i PltTotpChallenge
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.AttemptCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
