// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM plt_users
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM plt_users WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO plt_users (id, username, email, password_hash, role, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Enabled      bool      `json:"enabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Enabled,
	)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM plt_users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const findAllUsers = `-- name: FindAllUsers :many
SELECT id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
FROM plt_users
ORDER BY username ASC
`

func (q *Queries) FindAllUsers(ctx context.Context) ([]PltUser, error) {
	rows, err := q.db.Query(ctx, findAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltUser{}
	for rows.Next() {
		var i PltUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Enabled,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.AvatarUrl,
			&i.EmailNotificationsEnabled,
			&i.PushNotificationsEnabled,
			&i.Language,
			&i.Theme,
			&i.Layout,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.TotpBackupCodes,
			&i.FailedTotpAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
FROM plt_users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (PltUser, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
FROM plt_users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (PltUser, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
FROM plt_users
WHERE username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (PltUser, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const findUserPage = `-- name: FindUserPage :many
SELECT id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
FROM plt_users
ORDER BY username ASC
LIMIT $1 OFFSET $2
`

type FindUserPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindUserPage(ctx context.Context, arg FindUserPageParams) ([]PltUser, error) {
	rows, err := q.db.Query(ctx, findUserPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PltUser{}
	for rows.Next() {
		var i PltUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Enabled,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.AvatarUrl,
			&i.EmailNotificationsEnabled,
			&i.PushNotificationsEnabled,
			&i.Language,
			&i.Theme,
			&i.Layout,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.TotpBackupCodes,
			&i.FailedTotpAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :one
UPDATE plt_users
SET failed_login_attempts = failed_login_attempts + 1
WHERE id = $1
RETURNING failed_login_attempts
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedLoginAttempts, id)
	var failed_login_attempts int32
	err := row.Scan(&failed_login_attempts)
	return failed_login_attempts, err
}

const lockUserUntil = `-- name: LockUserUntil :exec
UPDATE plt_users SET locked_until = $2 WHERE id = $1
`

type LockUserUntilParams struct {
	ID          uuid.UUID          `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockUserUntil(ctx context.Context, arg LockUserUntilParams) error {
	_, err := q.db.Exec(ctx, lockUserUntil, arg.ID, arg.LockedUntil)
	return err
}

const resetLoginFailures = `-- name: ResetLoginFailures :exec
UPDATE plt_users SET failed_login_attempts = 0, locked_until = NULL WHERE id = $1
`

func (q *Queries) ResetLoginFailures(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginFailures, id)
	return err
}

const seedAdminUser = `-- name: SeedAdminUser :one
INSERT INTO plt_users (id, username, email, password_hash, role, enabled)
VALUES ($1, $2, $3, $4, 'ADMIN', true)
ON CONFLICT (username) DO NOTHING
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type SeedAdminUserParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) SeedAdminUser(ctx context.Context, arg SeedAdminUserParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, seedAdminUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const updateAvatarURL = `-- name: UpdateAvatarURL :one
UPDATE plt_users SET avatar_url = $2 WHERE id = $1
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type UpdateAvatarURLParams struct {
	ID        uuid.UUID `json:"id"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) UpdateAvatarURL(ctx context.Context, arg UpdateAvatarURLParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, updateAvatarURL, arg.ID, arg.AvatarUrl)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :one
UPDATE plt_users SET email = $2 WHERE id = $1
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type UpdateEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, updateEmail, arg.ID, arg.Email)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const updateLastActivity = `-- name: UpdateLastActivity :exec
UPDATE plt_users SET last_activity_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) UpdateLastActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastActivity, id)
	return err
}

const updateNotificationPreferences = `-- name: UpdateNotificationPreferences :one
UPDATE plt_users
SET email_notifications_enabled = $2, push_notifications_enabled = $3
WHERE id = $1
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type UpdateNotificationPreferencesParams struct {
	ID                        uuid.UUID `json:"id"`
	EmailNotificationsEnabled bool      `json:"email_notifications_enabled"`
	PushNotificationsEnabled  bool      `json:"push_notifications_enabled"`
}

func (q *Queries) UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, updateNotificationPreferences, arg.ID, arg.EmailNotificationsEnabled, arg.PushNotificationsEnabled)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE plt_users
SET password_hash = $2, failed_login_attempts = 0, locked_until = NULL
WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updatePreferences = `-- name: UpdatePreferences :one
UPDATE plt_users
SET language = $2, theme = $3, layout = $4
WHERE id = $1
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type UpdatePreferencesParams struct {
	ID       uuid.UUID `json:"id"`
	Language *string   `json:"language"`
	Theme    *string   `json:"theme"`
	Layout   *string   `json:"layout"`
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, updatePreferences,
		arg.ID,
		arg.Language,
		arg.Theme,
		arg.Layout,
	)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const updateUserEnabled = `-- name: UpdateUserEnabled :one
UPDATE plt_users SET enabled = $2 WHERE id = $1
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type UpdateUserEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) UpdateUserEnabled(ctx context.Context, arg UpdateUserEnabledParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, updateUserEnabled, arg.ID, arg.Enabled)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE plt_users SET role = $2 WHERE id = $1
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE plt_users SET username = $2 WHERE id = $1
RETURNING id, username, email, password_hash, role, enabled, created_at, last_activity_at,
       avatar_url, email_notifications_enabled, push_notifications_enabled,
       language, theme, layout, failed_login_attempts, locked_until,
       totp_secret, totp_enabled, totp_backup_codes, failed_totp_attempts
`

type UpdateUsernameParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (PltUser, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i PltUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.AvatarUrl,
		&i.EmailNotificationsEnabled,
		&i.PushNotificationsEnabled,
		&i.Language,
		&i.Theme,
		&i.Layout,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
		&i.FailedTotpAttempts,
	)
	return i, err
}
