// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMessageVote = `-- name: CreateMessageVote :one
INSERT INTO plt_message_votes (message_sync_id, user_id, direction)
VALUES ($1, $2, $3)
RETURNING id, message_sync_id, user_id, direction, created_at
`

type CreateMessageVoteParams struct {
	MessageSyncID string    `json:"message_sync_id"`
	UserID        uuid.UUID `json:"user_id"`
	Direction     int16     `json:"direction"`
}

func (q *Queries) CreateMessageVote(ctx context.Context, arg CreateMessageVoteParams) (PltMessageVote, error) {
	row := q.db.QueryRow(ctx, createMessageVote, arg.MessageSyncID, arg.UserID, arg.Direction)
	var i PltMessageVote
	err := row.Scan(
		&i.ID,
		&i.MessageSyncID,
		&i.UserID,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessageVote = `-- name: DeleteMessageVote :execrows
DELETE FROM plt_message_votes
WHERE user_id = $1 AND message_sync_id = $2
`

type DeleteMessageVoteParams struct {
	UserID        uuid.UUID `json:"user_id"`
	MessageSyncID string    `json:"message_sync_id"`
}

func (q *Queries) DeleteMessageVote(ctx context.Context, arg DeleteMessageVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessageVote, arg.UserID, arg.MessageSyncID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findMessageVote = `-- name: FindMessageVote :one
SELECT id, message_sync_id, user_id, direction, created_at
FROM plt_message_votes
WHERE user_id = $1 AND message_sync_id = $2
`

type FindMessageVoteParams struct {
	UserID        uuid.UUID `json:"user_id"`
	MessageSyncID string    `json:"message_sync_id"`
}

func (q *Queries) FindMessageVote(ctx context.Context, arg FindMessageVoteParams) (PltMessageVote, error) {
	row := q.db.QueryRow(ctx, findMessageVote, arg.UserID, arg.MessageSyncID)
	var i PltMessageVote
	err := row.Scan(
		&i.ID,
		&i.MessageSyncID,
		&i.UserID,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const listMessageVoteCounts = `-- name: ListMessageVoteCounts :many
SELECT
    message_sync_id,
    COUNT(*) FILTER (WHERE direction = 1)::INTEGER AS upvotes,
    COUNT(*) FILTER (WHERE direction = -1)::INTEGER AS downvotes
FROM plt_message_votes
WHERE message_sync_id = ANY($1::text[])
GROUP BY message_sync_id
`

type ListMessageVoteCountsRow struct {
	MessageSyncID string `json:"message_sync_id"`
	Upvotes       int32  `json:"upvotes"`
	Downvotes     int32  `json:"downvotes"`
}

func (q *Queries) ListMessageVoteCounts(ctx context.Context, messageSyncIds []string) ([]ListMessageVoteCountsRow, error) {
	rows, err := q.db.Query(ctx, listMessageVoteCounts, messageSyncIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageVoteCountsRow{}
	for rows.Next() {
		var i ListMessageVoteCountsRow
		if err := rows.Scan(&i.MessageSyncID, &i.Upvotes, &i.Downvotes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMessageVotes = `-- name: ListUserMessageVotes :many
SELECT message_sync_id, direction
FROM plt_message_votes
WHERE user_id = $1
  AND message_sync_id = ANY($2::text[])
`

type ListUserMessageVotesParams struct {
	UserID         uuid.UUID `json:"user_id"`
	MessageSyncIds []string  `json:"message_sync_ids"`
}

type ListUserMessageVotesRow struct {
	MessageSyncID string `json:"message_sync_id"`
	Direction     int16  `json:"direction"`
}

func (q *Queries) ListUserMessageVotes(ctx context.Context, arg ListUserMessageVotesParams) ([]ListUserMessageVotesRow, error) {
	rows, err := q.db.Query(ctx, listUserMessageVotes, arg.UserID, arg.MessageSyncIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMessageVotesRow{}
	for rows.Next() {
		var i ListUserMessageVotesRow
		if err := rows.Scan(&i.MessageSyncID, &i.Direction); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMessageForVote = `-- name: LockMessageForVote :one
SELECT id
FROM plt_messages
WHERE sync_id = $1 AND deleted = false
FOR UPDATE
`

func (q *Queries) LockMessageForVote(ctx context.Context, syncID string) (int64, error) {
	row := q.db.QueryRow(ctx, lockMessageForVote, syncID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateMessageVote = `-- name: UpdateMessageVote :execrows
UPDATE plt_message_votes
SET direction = $3
WHERE user_id = $1 AND message_sync_id = $2
`

type UpdateMessageVoteParams struct {
	UserID        uuid.UUID `json:"user_id"`
	MessageSyncID string    `json:"message_sync_id"`
	Direction     int16     `json:"direction"`
}

func (q *Queries) UpdateMessageVote(ctx context.Context, arg UpdateMessageVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMessageVote, arg.UserID, arg.MessageSyncID, arg.Direction)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
