CREATE TABLE plt_polls (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id      VARCHAR(36)  NOT NULL UNIQUE,
    creator_id   UUID         NOT NULL REFERENCES plt_users(id) ON DELETE CASCADE,
    question     VARCHAR(500) NOT NULL CHECK (LENGTH(BTRIM(question)) BETWEEN 1 AND 500),
    multi_choice BOOLEAN      NOT NULL DEFAULT FALSE,
    closed_at    TIMESTAMPTZ,
    deadline     TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_plt_polls_creator_id ON plt_polls(creator_id);
CREATE INDEX idx_plt_polls_open ON plt_polls(created_at DESC) WHERE closed_at IS NULL;

CREATE TABLE plt_poll_options (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id     BIGINT       NOT NULL REFERENCES plt_polls(id) ON DELETE CASCADE,
    position    SMALLINT     NOT NULL CHECK (position BETWEEN 0 AND 9),
    option_text VARCHAR(200) NOT NULL CHECK (LENGTH(BTRIM(option_text)) BETWEEN 1 AND 200),
    UNIQUE (poll_id, position),
    UNIQUE (poll_id, id)
);

CREATE INDEX idx_plt_poll_options_poll_id ON plt_poll_options(poll_id);
CREATE UNIQUE INDEX ux_plt_poll_options_text ON plt_poll_options(poll_id, LOWER(option_text));

CREATE TABLE plt_poll_votes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id    BIGINT      NOT NULL REFERENCES plt_polls(id) ON DELETE CASCADE,
    option_id  BIGINT      NOT NULL,
    user_id    UUID        NOT NULL REFERENCES plt_users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (poll_id, option_id, user_id),
    FOREIGN KEY (poll_id, option_id) REFERENCES plt_poll_options(poll_id, id) ON DELETE CASCADE
);

CREATE INDEX idx_plt_poll_votes_poll_user ON plt_poll_votes(poll_id, user_id);
CREATE INDEX idx_plt_poll_votes_user_id ON plt_poll_votes(user_id);
