package web

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"net/http"
	"strings"
)

const defaultContentSecurityPolicy = "default-src 'self'; script-src 'self' 'nonce-{nonce}'; style-src 'self'; img-src 'self' data:; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'"

// SecurityHeadersConfig controls the few policies that legitimately vary by
// deployment. CSP may contain {nonce}, which is replaced per request.
type SecurityHeadersConfig struct {
	ContentSecurityPolicy string
	PermissionsPolicy     string
	HSTS                  bool
}

// SecurityHeaders sets browser hardening headers and makes a CSP nonce
// available through CSPNonce.
func SecurityHeaders(config SecurityHeadersConfig) func(http.Handler) http.Handler {
	if config.ContentSecurityPolicy == "" {
		config.ContentSecurityPolicy = defaultContentSecurityPolicy
	}
	if config.PermissionsPolicy == "" {
		config.PermissionsPolicy = "camera=(), microphone=(), geolocation=()"
	}
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			nonce, err := newNonce()
			if err != nil {
				http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
				return
			}
			w.Header().Set("Content-Security-Policy", strings.ReplaceAll(config.ContentSecurityPolicy, "{nonce}", nonce))
			w.Header().Set("Permissions-Policy", config.PermissionsPolicy)
			w.Header().Set("Referrer-Policy", "no-referrer")
			w.Header().Set("X-Content-Type-Options", "nosniff")
			w.Header().Set("X-Frame-Options", "DENY")
			w.Header().Set("Cross-Origin-Opener-Policy", "same-origin")
			if config.HSTS {
				w.Header().Set("Strict-Transport-Security", "max-age=31536000; includeSubDomains")
			}
			next.ServeHTTP(w, r.WithContext(context.WithValue(r.Context(), nonceContextKey{}, nonce)))
		})
	}
}

// CSPNonce returns the per-request nonce generated by SecurityHeaders.
func CSPNonce(ctx context.Context) string {
	nonce, _ := ctx.Value(nonceContextKey{}).(string)
	return nonce
}

// NoStore prevents authentication and other sensitive responses from being
// retained by browser or intermediary caches.
func NoStore(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		next.ServeHTTP(w, r)
	})
}

// MaxBodyBytes rejects a declared oversized body before the next handler and
// retains a bounded reader for requests with missing or inaccurate lengths. A
// non-positive limit is a programmer error and panics at setup.
func MaxBodyBytes(limit int64) func(http.Handler) http.Handler {
	if limit <= 0 {
		panic("web: body limit must be positive")
	}
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.ContentLength > limit {
				http.Error(w, http.StatusText(http.StatusRequestEntityTooLarge), http.StatusRequestEntityTooLarge)
				return
			}
			r.Body = http.MaxBytesReader(w, r.Body, limit)
			next.ServeHTTP(w, r)
		})
	}
}

type nonceContextKey struct{}

func newNonce() (string, error) {
	value := make([]byte, 18)
	if _, err := rand.Read(value); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(value), nil
}
